/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mchuv
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public Integer[][] matrix;
    public int nRows, nColls;
    public boolean sumTaskRB, eqTaskRB;
    public String taskString;
    public MainJFrame() {
        initComponents();
        sumTaskRB = true;
        eqTaskRB = false;
        nRows = nColls = 2;
        matrix = new Integer[nRows][nColls];
        taskString = "Задание";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        QuitMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        WorkMenu = new javax.swing.JMenu();
        SelectMenu = new javax.swing.JMenu();
        SolveMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        QuitMenu.setText("Quit");
        QuitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitMenuMouseClicked(evt);
            }
        });
        QuitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuActionPerformed(evt);
            }
        });
        FileMenu.add(QuitMenu);

        jMenuBar1.add(FileMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        WorkMenu.setText("Work");

        SelectMenu.setText("Select");
        SelectMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectMenuMouseClicked(evt);
            }
        });
        SelectMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMenuActionPerformed(evt);
            }
        });
        WorkMenu.add(SelectMenu);

        SolveMenu.setText("Solve");
        SolveMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolveMenuMouseClicked(evt);
            }
        });
        WorkMenu.add(SolveMenu);

        jMenuBar1.add(WorkMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMenuActionPerformed

    private void QuitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_QuitMenuActionPerformed

    private void SelectMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectMenuActionPerformed

    private void SelectMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectMenuMouseClicked
        SelectDialog sd = new SelectDialog(this, false);
        sd.eqTaskRB.setSelected(true);
        sd.sumTaskRB.setSelected(false);
        sd.main = this;
        sd.setVisible(true);
        SelectMenu.setEnabled(false);
    }//GEN-LAST:event_SelectMenuMouseClicked

    private void QuitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_QuitMenuMouseClicked

    private void SolveMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolveMenuMouseClicked
        WorkDialog wd = new WorkDialog(this, false);
        wd.taskLabel.setText(taskString);
        wd.main = this;
        wd.setVisible(true);
        SolveMenu.setEnabled(false);
    }//GEN-LAST:event_SolveMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu QuitMenu;
    public javax.swing.JMenu SelectMenu;
    public javax.swing.JMenu SolveMenu;
    private javax.swing.JMenu WorkMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
