/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mchuv
 */
class Pair{
    public Integer first;
    public Integer second;
    Pair(int a, int b){
        first = a;
        second = b;
    }
    public void set(int a, int b){
        first = a;
        second = b;
    }
}


public class WorkDialog extends javax.swing.JDialog {

    /**
     * Creates new form WorkDialog
     */
    MainJFrame main;
    public WorkDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        GV1 = new javax.swing.JTable();
        taskLabel = new javax.swing.JLabel();
        eRows = new javax.swing.JTextField();
        eCols = new javax.swing.JTextField();
        btnSetRowsColls = new javax.swing.JButton();
        lAnswer = new javax.swing.JLabel();
        eNumber = new javax.swing.JTextField();
        btnGoSolve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        GV1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        GV1.setRowHeight(40);
        jScrollPane1.setViewportView(GV1);

        taskLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taskLabel.setText("Задание");

        eRows.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eRows.setText("Rows");

        eCols.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eCols.setText("Cols");

        btnSetRowsColls.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSetRowsColls.setText("Set");
        btnSetRowsColls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRowsCollsActionPerformed(evt);
            }
        });

        lAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lAnswer.setText("Ответ");

        eNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eNumber.setText("Число");

        btnGoSolve.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoSolve.setText("Solve!");
        btnGoSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoSolveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAnswer)
                    .addComponent(taskLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eCols)
                                    .addComponent(eRows)
                                    .addComponent(eNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSetRowsColls, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGoSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(taskLabel)
                .addGap(44, 44, 44)
                .addComponent(lAnswer)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(eNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnSetRowsColls)))
                        .addGap(75, 75, 75)
                        .addComponent(btnGoSolve, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Integer[][] Input(){
        String s;
        Integer temp;
        Integer[][] matrix = new Integer[GV1.getRowCount()][GV1.getColumnCount()];
        for (int i = 0; i < matrix.length; ++i)
        {
            for (int j = 0; j < matrix[i].length; ++j){
                s = GV1.getValueAt(j, i).toString();
                temp = Integer.parseInt(s);
                matrix[i][j] = temp;
            }
        }
        return matrix;
    }
    
    Pair MaxDigSum() {
        Integer max = Integer.MIN_VALUE;
        Pair res = new Pair(-1, -1);
        for (int i = 0; i < main.matrix.length; ++i) {
            for (int j = 0; j < main.matrix[i].length; ++j) {
                int n = Math.abs(main.matrix[i][j]);
                int sum = 0;
                while (n != 0)
                {
                    sum += n % 10;
                    n /= 10;
                }
                if (sum > max && main.matrix[i][j] > 0) {
                    max = sum;
                    res.set(i, j);
                }
            }
        }
        return res;
    }
    
    Pair FindFirstEq(int n) { 
        Pair res = new Pair(-1, -1);
        for (int i = 0; i < main.matrix.length; ++i) {
            for (int j = 0; j < main.matrix[i].length; ++j) {
                if(main.matrix[i][j] == n) {
                    res.set(i, j);
                    break;
                }
            }
            if (res.first != -1) break;
        }
        return res;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (main.matrix != null) {
            eRows.setText(String.valueOf(main.matrix.length));
            eCols.setText(String.valueOf(main.matrix[0].length));
            String[] titel = new String[main.matrix[0].length];
            for(int i = 0; i < titel.length; ++i){
                titel[i] = "Col " + i;
            }
            DefaultTableModel dtm = new DefaultTableModel(main.matrix, titel);
            GV1.setModel(dtm);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnGoSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoSolveActionPerformed
        // TODO add your handling code here:
        main.matrix = Input();
        if (main.sumTaskRB) {
            Pair idxs = MaxDigSum();
            lAnswer.setText("Ответ: (" + idxs.first + " : " + idxs.second + ")");
        }
        if (main.eqTaskRB) {
            int n = Integer.parseInt(eNumber.getText());
            Pair idxs = FindFirstEq(n);
            lAnswer.setText("Ответ: (" + idxs.first + " : " + idxs.second + ")");
        }
    }//GEN-LAST:event_btnGoSolveActionPerformed

    private void btnSetRowsCollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRowsCollsActionPerformed
        // TODO add your handling code here:
        int rows = Integer.parseInt(eRows.getText());
        int cols = Integer.parseInt(eRows.getText());
        DefaultTableModel dtm = (DefaultTableModel) GV1.getModel();
        dtm.setRowCount(rows);
        dtm.setColumnCount(cols);
        main.nRows = rows;
        main.nColls = cols;
    }//GEN-LAST:event_btnSetRowsCollsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        main.SolveMenu.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WorkDialog dialog = new WorkDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GV1;
    private javax.swing.JButton btnGoSolve;
    private javax.swing.JButton btnSetRowsColls;
    private javax.swing.JTextField eCols;
    private javax.swing.JTextField eNumber;
    private javax.swing.JTextField eRows;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAnswer;
    public javax.swing.JLabel taskLabel;
    // End of variables declaration//GEN-END:variables
}
